version: '2'
services:
  nginx:
    # используем последний стабильный образ nginx
    image: nginx:latest
    # маршрутизируем порты
    ports:
      - "8000:80"
    # монтируем директории, слева директории на основной машине, справа - куда они монтируются в контейнере
    volumes:
      - ./hosts:/etc/nginx/conf.d
      - ./www:/var/www
      - ./logs:/var/log/nginx
    # nginx должен общаться с php контейнером
    links:
      - php
    env_file:
      - .env
  php:
    # у нас свой образ для PHP, указываем путь к нему и говорим что его надо собрать
    build: ./images/php
    # этот образ будет общаться с mysql
    links:
      - mysql
    # монтируем директорию с проектами
    volumes:
      - ./www:/var/www
    env_file:
      - .env
  mysql:
    image: mariadb
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    # задаем пароль для root пользователя
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: Mirolsli1
  pma:
    # используем последний стабильный образ phpmyadmin
    image: phpmyadmin/phpmyadmin
    restart: always
    links:
      - mysql:mysql
    ports:
      - 8183:80
    env_file:
      - .env
#    environment:
#      # прописываем название нашего MySQL хоста
#      PMA_HOST: mysql
#      MYSQL_USERNAME: root
#      MYSQL_ROOT_PASSWORD: Mirolsli1
#